### ISSUE TITLE
Frequent crashes caused by Apothic Spawners in ATM10 modpack

### ISSUE THREAD

**Issue by SakuramuraYC** [Shadows-of-Fire/Apothic-Spawners#28]
Hello,
We have been experiencing frequent server crashes caused by the Apothic Spawners mod in the All The Mods 10 (ATM10) modpack. Crash reports indicate the issue originates from the tickDumbMobs event in Apothic Spawners, with server hang times exceeding 60000004 seconds, stuck during entity collision calculations involving VoxelShape processing.
Currently, we enable the “No AI” upgrade on the spawners and use fans to funnel mobs into a single spot for unified killing. However, this setup seemingly causes excessive stacking of no-AI entities, resulting in heavy collision calculations and eventually triggering watchdog crashes.
Crash report and latest server log are attached for your review and analysis:
•	Crash Report: https://mclo.gs/oLsbz41
•	Latest Log: https://mclo.gs/AQg97WW
We kindly ask for your assistance in confirming and optimizing this issue, hoping future updates can address the performance impact caused by no-AI mob stacking. Thank you for your continued maintenance and support of the mod!

**Comment by Shadows-of-Fire** [comment]
How many entities are you stacking that are causing the game to stall? Also the time that you've shown (`60000004 seconds`) is ~2 years. Are you _certain_ nothing else is happening?

**Comment by SakuramuraYC** [comment]
<img width="2564" height="1396" alt="Image" src="https://github.com/user-attachments/assets/36bb5fa2-c1ac-4c22-9881-00ac8d9186f4" />

<img width="657" height="468" alt="Image" src="https://github.com/user-attachments/assets/cdbecba2-81de-42bc-9b96-9b477524ca2c" />

This is our custom-designed kill zone, where monsters are concentrated using the MOD Fan system. The server experiences a crash roughly once every two days, but no abnormalities have been detected through Spark monitoring.

**Comment by malte0811** [comment]
> Also the time that you've shown (60000004 seconds) is ~2 years.

That looks like a Neo bug on 21.1 (fixed in the 21.2 port commit), [this](https://github.com/neoforged/NeoForge/blob/3b741364782a5f8e47a0c9218c518ba4739fd6a6/patches/net/minecraft/server/dedicated/ServerWatchdog.java.patch#L8) should be `NANOSECONDS_PER_SECOND` instead of `1000`. So the value is off by a factor 10^6 and the watchdog triggered after the expected 60 seconds.

**Comment by Shadows-of-Fire** [comment]
Well, that answers the number question. I don't think there is any action to take from my side here though; the timeout you are experiencing is not likely to be caused by Apoth.

The only "special" behavior the Apothic Spawners `NoAI` mobs receive is to still have their `travel()` method called, otherwise they don't respond to gravity or external forces. This would still be called for a mob _without_ `NoAI`, of course, so they're still less expensive than a normal entity.

https://github.com/Shadows-of-Fire/Apothic-Spawners/blob/72add512a557d7a27e00eb8137fc423c6ed3474a/src/main/java/dev/shadowsoffire/apothic_spawners/ASEvents.java#L119-L128
